services:
  - type: web
    name: nhl-predictions-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 prediction_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: FLASK_DEBUG
        value: false

